categories:
  - title: 'âœ¨ Features'
    labels:
      - 'feat'
      - 'feature'
      - 'refactor'
      - 'style'
  - title: 'ğŸ› Bug Fixes'
    labels:
      - 'fix'
  - title: 'ğŸ§° Maintenance'
    labels:
      - 'chore'
  - title: 'ğŸ§ª Testing'
    labels:
      - 'test'
  - title: 'ğŸ“„ Document'
    labels:
      - 'docs'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
exclude-labels:
  - 'skip-release-draft'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## File Changed

  $CHANGES
